version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:15
    container_name: postgres_notifications
    restart: unless-stopped
    environment:
      POSTGRES_USER: parkin
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: db_notifications
    ports:
      - "5334:5432"
    volumes:
      - postgres_notifications_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_notifications_data:
